// <auto-generated />
namespace LearnerProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_contactt_and_message_table_addedddd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_contactt_and_message_table_addedddd));
        
        string IMigrationMetadata.Id
        {
            get { return "202404260922001_mig_contactt_and_message_table_addedddd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
