// <auto-generated />
namespace LearnerProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mi_course_video : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mi_course_video));
        
        string IMigrationMetadata.Id
        {
            get { return "202404191707113_mi_course_video"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
